language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6

services:
  - redis-server

env:

before_script:
  - composer install --dev --prefer-source
  - echo "extension = redis.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini

script: phpunit --configuration phpunit.xml.dist --coverage-text

notifications:

